services:

  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/bitnami

  broker:
    image: bitnami/kafka:3.1
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/bitnami
    depends_on:
      - zookeeper

  request-receiver:
    build:
      context: ./request-receiver
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main
      - TOPIC=requests
      - CLIENT_ID=request-receiver
      - BROKER_HOST=broker
      - BROKER_PORT=9092
    ports:
      - 8080:5000
    depends_on:
      - broker

  status-receiver:
    build:
      context: ./status-receiver
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main
      - TOPIC=status-changes
      - CLIENT_ID=status-receiver
      - BROKER_HOST=broker
      - BROKER_PORT=9092
    ports:
      - 8081:5000
    depends_on:
      - broker

  assigner:
    build:
      context: ./assigner
      dockerfile: Dockerfile
    environment:
      - SUB_TOPICS=requests,status-changes
      - ASSIGNMENTS_TOPIC=assignments-commands
      - REQUESTS_TOPIC=requests
      - CLIENT_ID=assigner
      - GROUP_ID=assigner
      - BROKER_HOST=broker
      - BROKER_PORT=9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1
    depends_on:
      - redis
      - broker

  redis:
    image: redis:6.2

#  notifier:
#    build:
#      context: ./notifier
#      dockerfile: Dockerfile
#      environment:
#        - TOPICs=assignments
#        - GROUP_ID=notifier

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
