services:

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  broker:
    image: bitnami/kafka:3.1
    container_name: broker
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/bitnami
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  request-receiver:
    build:
      context: ./request-receiver
      dockerfile: Dockerfile
    container_name: request-receiver
    ports:
      - 8080:5000
    depends_on:
      - broker
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main
      - TOPIC=requests
      - CLIENT_ID=request-receiver
      - BOOTSTRAP_SERVER=broker:9092

  status-receiver:
    build:
      context: ./status-receiver
      dockerfile: Dockerfile
    container_name: status-receiver
    ports:
      - 8081:5000
    depends_on:
      - broker
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main
      - TOPIC=status-changes
      - CLIENT_ID=status-receiver
      - BOOTSTRAP_SERVER=broker:9092

  assigner:
    build:
      context: ./assigner
      dockerfile: Dockerfile
    container_name: assigner
    depends_on:
      - redis
      - broker
    environment:
      - SUB_TOPICS=requests,status-changes
      - ASSIGNMENTS_TOPIC=assignments-commands
      - REQUESTS_TOPIC=requests
      - CLIENT_ID=assigner
      - GROUP_ID=assigner
      - BOOTSTRAP_SERVER=broker:9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1

  redis:
    image: redis:6.2
    container_name: redis

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
